# Site settings
title:          Ryan Stark
description:    "Sophomore CS Student @ UMD"
url:            "https://hipsterironman.github.io"

# Author
author:
  name:         Ryan Stark
  email:        rstark13@umd.edu

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
